#!/bin/bash -e
#
# core tests for sheep 
#

#set -x

# change into sheeps base dir
cd $(dirname $0) && cd ..
export SHEEP_DIR=$(pwd)

# verify base directories
test -d modules
test -d library
test -d tests
test -d build
test -d cache
test -d cache/md5

# verify binaries
test -x sheep
test -x tests/test
test -x tests/true
test -x tests/false
test -x tests/core
test -x build/commit

# verify files
test -f library/core


#
# test core library functions
#

source library/core 

# test debug function
SHEEP_DEVELOP=
output=$(debug "testing debug")
test  "$output" == ""

SHEEP_DEVELOP=1
output=$(debug "testing debug")
test  "$output" == "testing debug"
SHEEP_DEVELOP=


# test get_md5_path
! get_md5_path
test "$(get_md5_path b05403212c66bdc8ccc597fedf6cd5fe)" == "${SHEEP_DIR}/cache/md5/b0/5403212c66bdc8ccc597fedf6cd5fe"

# test verify_cached_file
! verify_cached_file
echo 'test file' > "${SHEEP_DIR}/cache/md5/b0/5403212c66bdc8ccc597fedf6cd5fe"
verify_cached_file b05403212c66bdc8ccc597fedf6cd5fe
echo 'bad test file' > "${SHEEP_DIR}/cache/md5/b0/5403212c66bdc8ccc597fedf6cd5fe"
! verify_cached_file b05403212c66bdc8ccc597fedf6cd5fe > /dev/null
! test -f "${SHEEP_DIR}/cache/md5/b0/5403212c66bdc8ccc597fedf6cd5fe"
echo 'test file' > "${SHEEP_DIR}/cache/md5/b0/5403212c66bdc8ccc597fedf6cd5fe"

# test machine hash
machine_hash="$(machine_hash)"
test "$machine_hash" == 'OS X
10.7.2
x86_64' || test "$machine_hash" == 'Ubuntu
11.04
x86_64'

# test wipe_envirionment
export FOO=bar
export BAR=baz
wipe_envirionment
test $(env | wc -l ) -le 5

# test smart_parse
unset FOO BAR_BAZ
! smart_parse > /dev/null
! smart_parse --foo > /dev/null
! smart_parse -foo bar > /dev/null

test -z $FOO
test -z $BAR
test -z $BAZ

smart_parse --foo bar --bar-baz biz 

test "$FOO" == "bar"
test "$BAR_BAZ" == "biz"


unset ORIGIN MD5
required_inputs=(
  ORIGIN="http remote origin of a file"
  MD5="MD5 sum of remote file"
)
smart_parse --origin foo --md5 bar
test "$ORIGIN" == 'foo'
test "$MD5" == 'bar'
verify_inputs required_inputs[@]


unset ORIGIN MD5
required_inputs=(
  ORIGIN="http remote origin of a file"
  MD5="MD5 sum of remote file"
)
smart_parse --origin foo 
! verify_inputs required_inputs[@] > /dev/null
