#!/bin/bash -ex 

imagedir=$1

echo "deb http://127.0.0.1:3142/ubuntu natty main restricted universe multiverse" > $imagedir/etc/apt/sources.list

# change home to be inside chroot
export

# fix up grub defaults
sed -i.orig 's%GRUB_CMDLINE_LINUX_DEFAULT=.*%GRUB_CMDLINE_LINUX_DEFAULT="nosplash nomodeset text INIT_VERBOSE=yes init=/sbin/init -v noplymouth"%' $imagedir/etc/default/grub
sed -i.orig 's%GRUB_TIMEOUT=.*%GRUB_TIMEOUT=2%' $imagedir/etc/default/grub

cd `dirname $0`
cp chroot_script.sh ${imagedir}/root/chroot_script.sh
chmod +x ${imagedir}/root/chroot_script.sh
chroot $imagedir /root/chroot_script.sh 

#chroot $imagedir mv /sbin/initctl /sbin/initctl.bak
#chroot $imagedir dpkg-divert --local --rename --add /sbin/initctl
#chroot $imagedir ln -s /bin/true /sbin/initctl
#chroot $imagedir apt-get update 
#chroot $imagedir apt-get install -y libffi5 

# Ubuntu base doesn't have sudoers.d support by default.
mkdir -p /etc/sudoers.d
cat <<EOF > $imagedir/etc/sudoers
# User privilege specification
root	ALL=(ALL:ALL) ALL

# Members of the admin group may gain root privileges
%admin ALL=(ALL) ALL

## Read drop-in files from /etc/sudoers.d
## (the '#' here does not indicate a comment)
#includedir /etc/sudoers.d
EOF

# Script to grab the macaddress from ifconfig,
# download the kickseed and strip everything but the post install hook,
# run the kickseed script; then run /etc/firstboot
cat << EOF > $imagedir/root/seed.sh
#!/bin/bash
sed -i.orig -e 's/\/root\/seed.sh//' /etc/rc.local
macaddress=\$(ifconfig | awk '/eth0/ { print \$5 }')
curl http://192.168.20.11/machines/\${macaddress}/kickseed -o /root/kickseed
sed -i.orig -n '1h; 1!H; \${ g; s/^.*%post --interpreter=/#/ p }' /root/kickseed
chmod +x /root/kickseed
/root/kickseed 2>&1 > /root/kickseed.log
echo "exit 0" > /etc/rc.local
chmod +x /etc/firstboot
/etc/init.d/networking restart
echo "nameserver 8.8.8.8" > /etc/resolv.conf
/etc/firstboot 2>&1 > /root/firstboot.log
EOF
chmod +x $imagedir/root/seed.sh

cat << EOF >> $imagedir/etc/rc.local
/root/seed.sh
EOF
sed -i -e 's/exit 0//' $imagedir/etc/rc.local

#chroot $imagedir mv /sbin/initctl.bak /sbin/initctl
echo "deb http://mirror.anl.gov/ubuntu natty main restricted universe multiverse" > $imagedir/etc/apt/sources.list
sync 
