#!/bin/bash -ex 

imagedir=$1

# change home to be inside chroot
export 

echo psm > $imagedir/etc/hostname


cs_chef_dir=/home/jeremy/shared/cs-chef
pod_services_dir=/home/jeremy/shared/pod-services
mkdir ${imagedir}/root/cs-chef
rsync -a ${cs_chef_dir}/ ${imagedir}/root/cs-chef/
rsync -a ${pod_services_dir}/ ${imagedir}/root/pod-services/
cd `dirname $0`
cp install_chef.sh ${imagedir}/root/install_chef.sh
chmod +x ${imagedir}/root/install_chef.sh
sudo mount -t proc none ${imagedir}/proc
chroot $imagedir mv /sbin/initctl /sbin/initctl.bak
chroot $imagedir dpkg-divert --local --rename --add /sbin/initctl
chroot $imagedir ln -s /bin/true /sbin/initctl
chroot $imagedir apt-get update 
chroot $imagedir apt-get install -y libffi5 libavahi-compat-libdnssd-dev zeromq kyotocabinet
chroot $imagedir /root/install_chef.sh 
#sleep 3
chroot $imagedir /root/cs-chef/bin/install_cloudboot
chroot $imagedir mv /sbin/initctl.bak /sbin/initctl
sync 
sleep 2
sudo umount ${imagedir}/proc  
