#!/bin/bash -ex 

exit 0 

imagedir=$1

# change home to be inside chroot
export 

perl -pi -e "s%^127.0.1.1.*\n%%" $imagedir/etc/hosts
echo 'cloudboot' > $imagedir/etc/hostname
echo '127.0.0.1 cloudboot cloudboot.local' >> /etc/hosts
chroot $imagedir hostname cloudboot

cs_chef_dir=/home/martin/Dropbox/cloudscaling/cs-chef/
mkdir ${imagedir}/root/cs-chef
rsync -a ${cs_chef_dir}/ ${imagedir}/root/cs-chef/
cd `dirname $0`
cp install_chef.sh ${imagedir}/root/install_chef.sh
chmod +x ${imagedir}/root/install_chef.sh
sudo mount -t proc none ${imagedir}/proc
chroot $imagedir mv /sbin/initctl /sbin/initctl.bak
chroot $imagedir dpkg-divert --local --rename --add /sbin/initctl
chroot $imagedir ln -s /bin/true /sbin/initctl
chroot $imagedir apt-get update 
chroot $imagedir apt-get install -y libffi5
chroot $imagedir /root/install_chef.sh 
#sleep 3
chroot $imagedir /root/cs-chef/bin/install_cloudboot
chroot $imagedir mv /sbin/initctl.bak /sbin/initctl
sync 
sudo umount ${imagedir}/proc  
